package com.example.reservation.MemoryDao;

import android.provider.ContactsContract;

import com.example.reservation.contact.EmailAddress;
import com.example.reservation.dao.StoreOwnerDAO;
import com.example.reservation.domain.StoreOwner;
import java.util.ArrayList;
import java.util.List;


/**
 * A data access object (DAO) implementation for managing StoreOwner objects in memory.
 *
 * This class provides basic CRUD operations on a static in-memory list of store owners.
 */
public class StoreOwnerDAOMemory implements  StoreOwnerDAO {

    protected static List<StoreOwner> storeOwners  = new ArrayList<>();
    /**
     * Saves a store owner to the in-memory list.
     *
     * If the store owner does not already exist in the list, it is added.
     *
     * @param storeOwner The store owner to save.
     */

    @Override
    public void save(StoreOwner storeOwner) {
        if (!storeOwners.contains(storeOwner)) {
            storeOwners.add(storeOwner);
        }
    }

    /**
     * Deletes a store owner from the in-memory list.
     *
     * If the store owner does not exist in the list, no action is taken.
     *
     * @param storeOwner The store owner to delete.
     */

    @Override
    public void delete(StoreOwner storeOwner) {
        storeOwners.remove(storeOwner);
    }

    /**
     * Finds a store owner by their username.
     *
     * @param name The username of the store owner to find.
     * @return The store owner with the given username, or null if no such owner exists.
     */

    @Override
    public StoreOwner find(String name) {
        for (StoreOwner owner : storeOwners) { // Assuming storeOwners is a List<StoreOwner>
            if (owner.getUserName().equals(name)) {
                return owner;
            }
        }
        return null;
    }

    /**
     * Retrieves all store owners in the in-memory list.
     *
     * @return A new list containing all store owners.
     */

    @Override
    public List<StoreOwner> findAll() {
        return new ArrayList<>(storeOwners);
    }

    /**
     * Generates the next available ID for a new store owner.
     *
     * The ID is generated by incrementing the ID of the last store owner in the list,
     * or returns 1 if the list is empty.
     *
     * @return The next available store owner ID.
     */
    @Override
    public int nextId() {
        return (storeOwners.size() > 0 ? storeOwners.get(storeOwners.size()-1).getOwnerId()+1 : 1);
    }

}
