package com.example.reservation.MemoryDao;

import android.annotation.SuppressLint;

import com.example.reservation.dao.StoreDAO;
import com.example.reservation.domain.Request;
import com.example.reservation.domain.Store;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class StoreDAOMemory implements StoreDAO {

    private static List<Store> stores = new ArrayList<>();

    /**
     * Retrieves all stores in the in-memory list.
     *
     * @return A new list containing all stores.
     */

    @Override
    public List<Store> findAll() {
        return new ArrayList<>(stores);
    }

    /**
     * Finds a store by its ID.
     *
     * @param storeId The ID of the store to find.
     * @return The store with the specified ID, or null if no such store exists.
     */

    @Override
    public Store find(int storeId) {
        // Use '==' to compare primitive int values
        for (Store store : stores) {
            if (store.getStoreId() == storeId) {
                return store;
            }
        }
        return null;
    }

    /**
     * Deletes a store from the in-memory list.
     *
     * If the store does not exist in the list, no action is taken.
     *
     * @param entity The store to delete.
     */
    @Override
    public void delete(Store entity) {
        stores.remove(entity);
    }

    /**
     * Saves a store to the in-memory list.
     *
     * @param store The store to save.
     */

    @Override
    public void save(Store store) {
        stores.add(store);
    }

    /**
     * Finds all stores owned by a specific owner.
     *
     * @param ownerId The ID of the owner whose stores to find.
     * @return A list of stores owned by the specified owner.
     */

    @Override
    public List<Store> findAllByOwnerId(int ownerId) {
        List<Store> ownerStores = new ArrayList<>();
        for (Store store : stores) {
            // Use '==' to compare primitive int values
            if (store.getOwnerId() == ownerId) {
                ownerStores.add(store);
            }
        }
        return ownerStores;
    }

    // Add a new store
    /**
     * Adds a new store to the in-memory list.
     *
     * @param store The store to add.
     */
    public void addStore(Store store) {
        stores.add(store);
    }

    /**
     * Finds all stores located in a specific address.
     *
     * @param address The address to search for (e.g., city or street).
     * @return A set of stores located in the specified address.
     */
    @Override
    public Set<Store> findByLocation(String address) {
        Set<Store> result = new HashSet<>();
        for(Store s: stores){
            if (s.getAddress().getCity().contains(address)){
                result.add(s);
            }
        }
        return result;
    }

    /**
     * Finds all stores belonging to a specific category.
     *
     * @param category The category to search for.
     * @return A set of stores in the specified category.
     */

    @Override
    public Set<Store> findByCategory(String category) {
        Set<Store> result = new HashSet<>();
        for(Store s: stores){
            if (s.getCategory().contains(category)){
                result.add(s);
            }
        }
        return result;
    }

    /**
     * Generates the next available ID for a new store.
     *
     * The ID is generated by incrementing the ID of the last store in the list,
     * or returns 1 if the list is empty.
     *
     * @return The next available store ID.
     */

    @Override
    public int nextId() {
        return (stores.size() > 0 ? stores.get(stores.size()-1).getStoreId()+1 : 1);
    }
}

